gemini_api_key: ""
openai_api_key: ""
openrouter_api_key: ""
claude_api_key: ""
ai_provider: "gemini" # Pode ser "gemini", "gpt", "openrouter" ou "claude"
openai_model: "gpt-3.5-turbo" # Opcional
openai_max_tokens: "2048" # Opcional
openai_temperature: "0.7" # Opcional
openrouter_model: "microsoft/wizardlm-2-8x22b" # Opcional
openrouter_max_tokens: "2048" # Opcional
openrouter_temperature: "0.7" # Opcional
claude_model: "anthropic/claude-3-haiku" # Opcional
claude_max_tokens: "4096" # Opcional
claude_temperature: "0.7" # Opcional
home_dir: "C:\\Users\\Usuario\\.zion"
plugins_dir: "C:\\Users\\Usuario\\.zion\\plugins"