package ai

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ExtractAndCreateProject extrai diretamente os diretórios e arquivos do JSON
// e cria a estrutura do projeto sem tentar interpretar o conteúdo
func ExtractAndCreateProject(projectName string, jsonStr string) error {
	// Remover blocos de código markdown se presentes
	if strings.HasPrefix(jsonStr, "```json\n") && strings.HasSuffix(jsonStr, "\n```") {
		jsonStr = strings.TrimPrefix(jsonStr, "```json\n")
		jsonStr = strings.TrimSuffix(jsonStr, "\n```")
	}

	var scaffoldResp ScaffoldResponse
	err := json.Unmarshal([]byte(jsonStr), &scaffoldResp)
	if err != nil {
		return fmt.Errorf("erro ao fazer parse do JSON: %v", err)
	}

	// Criar o diretório raiz do projeto
	if err := os.MkdirAll(projectName, 0755); err != nil {
		return fmt.Errorf("erro ao criar diretório raiz '%s': %v", projectName, err)
	}
	fmt.Printf("\n📁 Criando diretório raiz: %s\n", projectName)

	// Criar diretórios
	if len(scaffoldResp.Structure.Directories) > 0 {
		fmt.Println("\n📂 Criando diretórios:")
		for _, dir := range scaffoldResp.Structure.Directories {
			dirPath := filepath.Join(projectName, dir)
			fmt.Printf("   ├── %s\n", dir)
			if err := os.MkdirAll(dirPath, 0755); err != nil {
				return fmt.Errorf("erro ao criar diretório '%s': %v", dir, err)
			}
		}
	}

	// Processar cada arquivo
	if len(scaffoldResp.Structure.Files) > 0 {
		fmt.Println("\n📄 Criando arquivos:")

		// Verificar se package.json existe
		hasPackageJson := false
		for filePath := range scaffoldResp.Structure.Files {
			if filePath == "package.json" {
				hasPackageJson = true
				break
			}
		}

		// Se não houver package.json e for um projeto TypeScript/JavaScript, criar um padrão
		if !hasPackageJson && (strings.Contains(strings.ToLower(projectName), "ts") ||
			strings.Contains(strings.ToLower(projectName), "js")) {
			scaffoldResp.Structure.Files["package.json"] = map[string]interface{}{
				"name":        projectName,
				"version":     "1.0.0",
				"description": "Generated by Zion",
				"main":        "dist/index.js",
				"scripts": map[string]string{
					"build": "tsc",
					"start": "node dist/index.js",
					"dev":   "nodemon src/index.ts",
				},
				"dependencies": map[string]string{
					"express": "^4.18.2",
				},
				"devDependencies": map[string]string{
					"@types/express": "^4.17.17",
					"@types/node":    "^20.4.5",
					"nodemon":        "^3.0.1",
					"typescript":     "^5.1.6",
				},
			}
			fmt.Println("   ℹ️  package.json não encontrado, criando versão padrão")
		}

		for filePath, content := range scaffoldResp.Structure.Files {
			var contentStr string

			switch content := content.(type) {
			case map[string]interface{}:
				if fileContent, ok := content["content"]; ok {
					switch fc := fileContent.(type) {
					case string:
						contentStr = ProcessEscapedChars(fc)
					case map[string]interface{}:
						// Se o conteúdo é um objeto JSON (ex: package.json)
						if filePath == "package.json" {
							ProcessPackageJsonContent(fc)
						}
						jsonBytes, err := json.MarshalIndent(fc, "", "  ")
						if err != nil {
							return fmt.Errorf("erro ao serializar conteúdo JSON para '%s': %v", filePath, err)
						}
						contentStr = string(jsonBytes)
					}
				} else {
					// Se não tem "content", assume que o map é o conteúdo direto (para package.json)
					if filePath == "package.json" {
						ProcessPackageJsonContent(content)
					}
					jsonBytes, err := json.MarshalIndent(content, "", "  ")
					if err != nil {
						return fmt.Errorf("erro ao serializar conteúdo direto para '%s': %v", filePath, err)
					}
					contentStr = string(jsonBytes)
				}
			case string:
				if filePath == "package.json" {
					// Se package.json vier como string, tentar fazer parse e processar
					var jsonContent map[string]interface{}
					if err := json.Unmarshal([]byte(content), &jsonContent); err == nil {
						ProcessPackageJsonContent(jsonContent)
						jsonBytes, err := json.MarshalIndent(jsonContent, "", "  ")
						if err != nil {
							return fmt.Errorf("erro ao serializar package.json processado: %v", err)
						}
						contentStr = string(jsonBytes)
					} else {
						contentStr = ProcessEscapedChars(content)
					}
				} else {
					contentStr = ProcessEscapedChars(content)
				}
			}

			// Skip empty files
			if strings.TrimSpace(contentStr) == "" {
				fmt.Printf("   ⚠️  Pulando arquivo vazio: %s\n", filePath)
				continue
			}

			fullPath := filepath.Join(projectName, filePath)
			fmt.Printf("   ├── %s\n", filePath)

			// Garantir que o diretório pai exista
			parentDir := filepath.Dir(fullPath)
			if err := os.MkdirAll(parentDir, 0755); err != nil {
				return fmt.Errorf("erro ao criar diretório pai para '%s': %v", filePath, err)
			}

			if err := os.WriteFile(fullPath, []byte(contentStr), 0644); err != nil {
				return fmt.Errorf("erro ao criar arquivo '%s': %v", filePath, err)
			}
		}
	}

	// Exibir resumo
	fmt.Printf("\n📊 Resumo da estrutura criada:\n")
	fmt.Printf("   ├── %d diretórios\n", len(scaffoldResp.Structure.Directories))
	fmt.Printf("   └── %d arquivos\n", len(scaffoldResp.Structure.Files))

	return nil
}
